### PR TITLE
Adjust logo

### PR DESCRIPTION
**Pull request by eteq**
Sadly the new most excellent logo @pllim contributed in #316 cannot last forever.  I suppose it deserves a full 24 hours given that it's a bout a "special day", though, so we should wait for at least 6 hours before merging this.  And I'm definitely not saying that because a certain pair of :cat:s gave me a judgemental look demanding their fair share of fame.

### CODE REVIEW

**Comment by pllim** [comment]
You might also want to squash it out in `master` itself (or just drop my special commits altogether) to get rid of them from the repo footprint.

**Comment by pllim** [comment]
Or if you fancy some JavaScript, maybe can even have a conditional to only show special logo on special day without reverting anything! :wink:

**Comment by eteq** [comment]
Ooh, tempting, perhaps the JS trick could be a project for 2020, @pllim ? :wink:

I think the squash isn't necessary though as it's ~1 per year and they aren't that big of files.  I kinda like having this in the git history anyway.

**Comment by pllim** [comment]
I am just gonna drop these links here...

https://stackoverflow.com/questions/492994/compare-two-dates-with-javascript

https://stackoverflow.com/questions/17249340/conditionally-load-images-for-responsive-designs

**Comment by astrofrog** [comment]
@pllim - I think the default logo should load the normal way and JS should be used to conditionally replace the image - we don't want the logo to have to be shown using JS under normal conditions.

**Comment by pllim** [comment]
See #318 for **alternate solution**.

**Comment by bsipocz** [comment]
I'm afraid it's time to say goodbye for the cats 😿

**Pull request merged**
