### PR TITLE
Add spherical-geometry affiliated package

### PR DESCRIPTION
**Pull request by mdboom**

### CODE REVIEW

**Comment by mdboom** [comment]
ping?  (I don't have merge rights to this repo, or I'd hit that button).

**Comment by mdboom** [comment]
:wave: ?

**Comment by embray** [comment]
Apparently I have merge rights to this repo.  Not sure where everyone else was :P

**Comment by embray** [comment]
I assume this will kick of a rebuild of the website too.

**Comment by embray** [comment]
Oh I see, it just uses javascript, so nothing to rebuild.  I guess that's fine.

**Comment by eteq** [comment]
@embray @mdboom - just so that we're on the same page, adding new affiliated packages (that is, actually doing the merge, of course the PR can be done by anyone) should be done by members of the coordinating committee.  Not a big deal for this one, of course, but this is one area where we have established "rules" already written down, so I think it's better if we stick with that for consistency's sake in the future.

**Comment by embray** [comment]
Ah, I wasn't aware.  That's fine.

**Pull request merged**
