### PR TITLE
Fixes #42 seperates the table based on provisional column

### LINKED ISSUE #42: Separate table of provisional vs accepted packages

### PR DESCRIPTION
**Pull request by sudheesh001**
screen shot 2014-11-27 at 3 26 26 pm

### CODE REVIEW

**Comment by sudheesh001** [comment]
@astrofrog @eteq Could you have a look at this if possible ? I am looking forward to contribute more to this project and the website.

**Comment by eteq** [comment]
@sudheesh001 - sorry about this, somehow the notification for this dropped off my radar and only just noticed it while looking.  I will aim to review this tomorrow.

**Comment by sudheesh001** [comment]
Cool!! Looking forward to having this patch merged today.

**Comment by eteq** [comment]
@sudheesh001 - a couple things:

1. It looks to me like you've got which is in which table backwards.  Packages where 'provisional' is 'false' are *not* provisional.  If they have a date, they *are* provisional.  But in the version you have here, that's swapped.  So I think you just need to switch them around.
2. Now that there's a separate section, it might be good to add a 'next review date' column to the provisional packages.  That's what the meaning of the dates are (when 'provisional' is not 'false').  If you'd rather not do that in this PR that's ok too, but it might make sense while you're thinking about it.

One other minor item: I see above that you've been squashing/amending your changes so that there's only one commit for this PR.  In general, we prefer that you *not* do this: it's better to actually keep a record of the changes, as well as the context of the comment thread here.  Squashing or amending should really only be done in special circumstances (i.e., you accidentally committed a password, or a large binary file that would make the repository awkwardly large).  So in the future I suggest instead you just push up new commits.

**Comment by eteq** [comment]
@sudheesh001 - can you try to make the changes I've mentioned above?

**Comment by sudheesh001** [comment]
@eteq , Fixed those changes of getting the changes on the table backwards. It looks like it's good to go now.

I think its best to file a new issue for the adding a next review date column for provisional packages and then i'd be more than happy to send a patch to that, once this is merged. I'll be opening an issue for this.


>One other minor item: I see above that you've been squashing/amending your changes so that there's only one commit for this PR. In general, we prefer that you not do this: it's better to actually keep a record of the changes, as well as the context of the comment thread here. Squashing or amending should really only be done in special circumstances (i.e., you accidentally committed a password, or a large binary file that would make the repository awkwardly large). So in the future I suggest instead you just push up new commits.

The other open source organizations i've pushed patches to always asked for this, so I guess it kind of became a habit :yum: Pushed the commit normally this time.

**Comment by embray** [comment]
Hmm, not to cause confusion (sorry @sudheesh001) but I actually prefer that PR authors squash their commits, at least at the end of review / before merge.  I'm not saying it should be squashed down to a *single* commit, but typo fixes and other fixes made in response to review I think should be squashed down into a minimal, cohesive set of changes.  I do this myself manually on some PRs that have a mess of a history, though it's nice when contributors can do this themselves as well :)

Again, my preference is to do it just prior to merging though.

**Comment by sudheesh001** [comment]
@embray Thats a good thing to follow, I'll squash it into one if the review passes from any of the Collaborators or Owners.

**Pull request merged**
