### PR TITLE
Added reproject to list of affiliated packages

### PR DESCRIPTION
**Pull request by astrofrog**
@eteq @perrygreenfield - would it be ok to add reproject as an affiliated package?

@eteq - what should I be setting for the provisional date?

### CODE REVIEW

**Comment by eteq** [comment]
Yes, I'm ok with this.  For provisional, do one year from now - that's the standard we've been using.

**Comment by astrofrog** [comment]
@eteq - just to check, if a package is ready sooner (this one isn't yet) there's no reason we have to wait a year to approve it, right?

**Comment by astrofrog** [comment]
@eteq - requested this on the list in https://groups.google.com/forum/#!topic/astropy-dev/B05JF9KomiI

**Comment by astrofrog** [comment]
@eteq - no objections, so can we merge this?

**Comment by eteq** [comment]
@astrofrog - yep, looks good.  Merging!

**Pull request merged**
