### PR TITLE
Update constants maintainers

### PR DESCRIPTION
**Pull request by pllim**
As discussed in coordination meeting. c/c @taldcroft @stargaser @mhvk

### CODE REVIEW

**Comment by mhvk** [comment]
Great, thanks @stargaser for volunteering (or were you volunteered?!?).

**Comment by pllim** [comment]
@stargaser volunteered himself, but @mhvk was volunteered... 😉

**Comment by mhvk** [comment]
Hmm, well, since I didn't even remember *not* being deputy, I guess that is fine...

**Comment by bsipocz** [comment]
Well, everyone OK-ed this, so merging away.

**Comment by eteq** [comment]
@bsipocz @mhvk @pllim - just a quick FYI so you all know: when the "roles" file is updated you have to run the ``update_roles.py`` script to get the html to update.  I'll just do this in master, not a problem, but just bear that in mind for any future such items.

**Comment by eteq** [comment]
Also, just in case anyone comes across this PR in the future: role changes are nominally the purvue of the Coordination committee.  This particular change was fine/great, because it came out of a discussion at the coordination meeting and the people involved were there in person.  But just wanted to make it clear in case people are wandering around and come across this PR...

**Comment by pllim** [comment]
Ops, sorry.

**Comment by mhvk** [comment]
@eteq - while doing an update in master, could you also add a comment in this file saying one has to run `update_roles.py`?

**Pull request merged**
