### PR TITLE
Request of affiliation for agnpy

### PR DESCRIPTION
**Pull request by cosimoNigro**
Dear astropy developers,

I'd like to submit to your attention `agnpy`, a package computing the photon spectra produced by leptonic radiative processes in jetted Active Galactic Nuclei (AGN). 
Starting from a parametrised non-thermal electron distribution (contained in a simplified emission region streaming along the galaxy jet) `agnpy` computes the spectral energy distribution (SEDs) generated by synchrotron radiation and Compton scattering. Photoabsorption by gamma-gamma pair production can be also considered.

`agnpy` is built on the numpy + astropy ecosystem: all the numerics is delegated to numpy, while input and output physical quantities are casted as astropy `Quantities`. For this reason I would like my package to be considered for the affiliation.

Here the link to the repository:
https://github.com/cosimoNigro/agnpy
and here the link to the documentation:
https://agnpy.readthedocs.io/en/latest/

Examples of usage are available in the documentation and in the `tutorials` directory in the GitHub repository.

Best Regards,

Cosimo

### CODE REVIEW

**Comment by cosimoNigro** [comment]
Hello, 

today I tried to send a message to the google group indicated on [this page](https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_process.md#proposing-an-affiliated-package)
https://groups.google.com/forum/#!forum/astropy-dev

Sorry for not having done that before.
I tried to publish twice a message advertising the package but I cannot see it displayed in the main forum. Do I need some access right to publish a message in the google group.

Anyway was my request taken into consideration even without sending the e-mail?

Thanks

**Comment by taldcroft** [comment]
@cosimoNigro - we'll check into the email to astropy-dev, but in any case this PR is sufficient for now.  Thanks!

**Comment by taldcroft** [comment]
The astropy-dev email has been approved and posted.

**Comment by hamogu** [comment]
Hi @cosimoNigro ,

This is an update about the status of your request to make agnpy an Astropy affiliated package. We have just taken over the role as
affiliated package editors. We apologize for the delay in reviewing your package and we are working on it. Thank you for your interest and continued patience.

Sincerely,
@hamogu and @pllim

**Comment by cosimoNigro** [comment]
HI @hamogu,

no problems at all for the waiting.
Yesterday I made a new release (0.0.6) in which I improved the documentation.
Would it be possible to take this latest release into account for your review?

In any case thank you and all the best.

**Comment by hamogu** [comment]
We always as the reviewer to review the current or latest branch, so: "yes"!

**Comment by hamogu** [comment]
Thank you for proposing this package as an affiliated package! I'm happy to confirm that we've found a reviewer and your package is now under review and we'll post the results of the review here and on the mailing list.

**Comment by hamogu** [comment]
We've received the referee's report and I have looked over the package myself, too. We think it's a great addition to the affiliated package list except for one point: We note that the test coverage is pretty low (< 50% last time I checked). We'll accept this as an affiliated package once the test coverage is improved. We don't have an exact limit, because some package might contain code that is hard to test or where a significant fraction of the lines is not very important for the functionality and the authors decided not to do test for that (e.g. old deprecated plotting back-end), but 60-80 % coverage is a number that most packages reach.

I know that that's something you are working on (https://github.com/cosimoNigro/agnpy/issues/20 and https://github.com/cosimoNigro/agnpy/pull/26).
Just put a comment in this thread when you are happy with your test coverage and we'll accept the package and merge this PR right way.

**Comment by cosimoNigro** [comment]
Hello @hamogu,
many thanks to you and the reviewer for taking the time to review the package.
I'll get back to you as soon as I get to a larger test coverage and close [cosimoNigro/agnpy#26](https://github.com/cosimoNigro/agnpy/issues).
Thank you,

Cosimo

**Comment by cosimoNigro** [comment]
Hello @hamogu,
with [cosimoNigro/agnpy#32](https://github.com/cosimoNigro/agnpy/pull/32) I have reached a code coverage of 78%.
Cheers,
Cosimo

**Comment by hamogu** [comment]
This package has been reviewed for inclusion in the Astropy affiliated package
ecosystem by a member of the Astropy community as well as myself, and I have
synthesized the results of the review here.

You can find out more about our review criteria in
[Reviewing affiliated packages](https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md).
For each of the review categories below we have listed the score and have
included some comments when the score is not green.

<table>
<tr><td><b>Functionality/Scope</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#functionality-functionality">
General package
</a></td></tr>

<tr><td colspan=2><i>The agnpy package represents a specialized package​ ​useful for astronomers interested in modelling broadband spectra produced by leptonic radiation processes in AGNs.</i></td></tr>

<tr><td><b>Integration with Astropy ecosystem</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#integration-with-astropy-ecosystem--ecointegration">
Orange
</a></td></tr>

<tr><td colspan=2><i>The agnpy package uses Astropy for handling units, constants and distance computations. Astropy is used in most places appropriately. In single places the code could be simplified using more recent Astropy features. It is worth considering if the `spectra.py` sub-package could re-use
model implementations as well as base classes from `astropy.modelling.models`. However there is currently no intended support for fitting spectral models, so the benefit from using Astropy models is not obvious (except for API compatibility). An integration of features provided by the specutils and naima packages, as well as Astropy models could be considered in future if a fitting interface is added.</i></td></tr>

<tr><td><b>Documentation</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#documentation-documentation">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Testing</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#testing-testing">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Development status</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#development-status-devstatus">
Heavy Development
</a></td></tr>

<tr><td colspan=2><i>The agnpy package is fairly young (started end of 2019) and there is no major release yet.
The user base is probably still very limited and given the minor version number of 0.0.6 chosen by the authors it looks like heavy development and possibly breaking API changes are still possible.</i></td></tr>

<tr><td><b>Python 3 compatibility</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#python-3-compatibility-python3">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

</table>

**Summary/Decision**: This package meets the review criteria for affiliated
packages, so we are happy to confirm that we'll be listing your package as an
affiliated package! Keep up the good work, and we encourage you to improve on
the areas above that weren't “green” yet.

If you have any follow-up questions or disagree with any of the comments above,
leave a comment and we can discuss it here. At any point in future you can
request a re-review of the package if you believe any of the scores should be
updated - contact the affiliated package editors
[listed on the Astropy team page](https://www.astropy.org/team),
and we will do a new review.

I will edit the registry.json file and merge with PR once the CI passes.

**Pull request merged**
