### PR TITLE
Add timeseries maintainer role

### LINKED ISSUE #322: Add timeseries to roles
I'm happy to be the Lead maintainer to start with

### PR DESCRIPTION
**Pull request by eteq**
Closes #322.

Note that this should not be merged until 3.2 is released since it's only then that the sub-package is "official".

cc @astrofrog (who volunteered in #322)

### CODE REVIEW

**Comment by astrofrog** [comment]
Looks good but can we please re-arrange the JSON to be more intuitive! 😆

**Comment by eteq** [comment]
Preaching to the choir, @astrofrog! (but you're right we should make an issue about that...)

**Comment by bsipocz** [comment]
we talked about it off band, but for the record here: I volunteer to be deputy

**Comment by eteq** [comment]
3.2 is out, so merging now!

**Pull request merged**
