### PR TITLE
Add "baseband" to the repository

### PR DESCRIPTION
**Pull request by mhvk**
Part of the submission of baseband as an affiliated package.

### CODE REVIEW

**Comment by astrofrog** [comment]
Thank you for proposing this package to the Astropy affiliated package ecosystem! I'm very sorry about the delay in getting this package reviewed 🙏 - as you know we have been working on finalizing a [new review workflow](https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_process.md) and have only just managed to finalize it.

Could you rebase this pull request to resolve the conflicts, and then also add empty sections to the ``review`` section as described in [proposing an affiliated package](https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_process.md#proposing-an-affiliated-package)? I'll be assigning a reviewer shortly for this package, and will get back to you soon.

**Comment by mhvk** [comment]
@astrofrog - OK, thanks. I resolved the conflicts and added the review section.

**Comment by astrofrog** [comment]
This package has been reviewed for inclusion in the Astropy affiliated package ecosystem by a member of the Astropy community as well as myself, and I have synthesized the results of the review here.

You can find out more about our review criteria in [Reviewing affiliated packages](https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md). For each of the review categories below we have listed the score and have included some comments when the score is not green.

<table>
<tr><td><b>Functionality/Scope</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#functionality-functionality">
Specialized package
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Integration with Astropy ecosystem</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#integration-with-astropy-ecosystem--ecointegration">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Documentation</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#documentation-documentation">
Green
</a></td></tr>

<tr><td colspan=2><i>Very minor comments: the logo in the top left of the docs just says 'package template', and the Travis badge on the home page of the docs doesn't link to Travis.</i></td></tr>

<tr><td><b>Testing</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#testing-testing">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Development status</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#development-status-devstatus">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Python 3 compatibility</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#python-3-compatibility-python3">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

</table>

**Summary/Decision**: Everything looks great, and we're happy to confirm that this package is accepted as an affiliated package! :trophy:

If you have any follow-up questions or disagree with any of the comments above, leave a comment and we can discuss it here. At any point in future you can request a re-review of the package if you believe any of the scores should be updated - contact the coordination committee, and we’ll do a new review.

**Comment by mhvk** [comment]
@astrofrog - great to hear that the review was so positive (and thanks for noticing the minor issues with the documentation...). Should this PR now be merged, or is it all done already?

**Comment by astrofrog** [comment]
@mhvk - merged now :)

**Pull request merged**
