### PR TITLE
BOT: Revive Giles

### PR DESCRIPTION
**Pull request by pllim**
@Cadair , did you mean this or something else? How do we get Giles to do website preview for PRs here again?

### CODE REVIEW

**Comment by pllim** [comment]
Hmm didn't work?

**Comment by bsipocz** [comment]
or switch to use https://github.com/scientific-python/circleci-artifacts-redirector-action, that one is quite widely used.

**Comment by pllim** [comment]
Oh, indeed https://github.com/scientific-python/circleci-artifacts-redirector-action works. It is in `main` now. Thanks!

**Comment by pllim** [comment]
For completeness, I removed the Giles app from this repo.

**Pull request closed without merging**
