### PR TITLE
Remove Dan from roles

### PR DESCRIPTION
**Pull request by pllim**
Sadly...

### CODE REVIEW

**Comment by bsipocz** [comment]
😢

**Comment by eteq** [comment]
Sadly, this is probably accurate. 

@drdavella, can you confirm you want to resign from these (vs interested in trying to carry on in free time)?

**Comment by drdavella** [comment]
😭 
I'd love to stay involved and hopefully I'll be able to contribute a bit here and there, but realistically I don't think I'm going to have a lot of time to commit to these roles.
😭

**Comment by eteq** [comment]
> realistically I don't think I'm going to have a lot of time to commit to these roles

😭 (but totally understandable, and we appreciate whatever time you have!)

**Pull request merged**
