### PR TITLE
Added license

### PR DESCRIPTION
**Pull request by astrofrog**
I guess we should leave this open for a couple of weeks in case any contributors have objections.

Since in principle this would require agreement from all contributors, as a middle ground I'll ping the top 10 contributors (according to GitHub): @eteq @taldcroft @granttremblay @mdboom @bsipocz @abostroem @kelle @pllim @embray - feel free to ignore if you don't care or are happy with this - just put a comment if you object.

Fixes https://github.com/astropy/astropy.github.com/issues/198

### CODE REVIEW

**Comment by pllim** [comment]
I am okay with the license type and content. My nitpick is that I desire its formatting to be picked up the GitHub such that it appears on the top bar of the repo, if you know what I mean. Thanks!

**Comment by pllim** [comment]
p.s. If this is the same as https://github.com/astropy/astropy/blob/master/LICENSE.rst , I guess GitHub would pick it up?

**Comment by astrofrog** [comment]
@pllim I copied and pasted it from the astropy core repo so it should be ok :)

**Comment by eteq** [comment]
There were no major objections so I'll just merge this.

**Pull request merged**
