### PR TITLE
Website Reorganization

### PR DESCRIPTION
**Pull request by abostroem**
- Made About a drop down menu
    - Moved team to About menu
    - Moved "acknowledging and citation" to About menu
    - Moved "code of conduct" to About menu
    - Moved Overview from readthedocs to About in About menu
- Moved "Report an Issue" from readthedocs to Contributing
- Reorganized main page
- Added more details to git help

### CODE REVIEW

**Comment by bsipocz** [comment]
I rememberer a long discussion last year when we exposed the ``Team`` from the hidden about to the upper level. I think that should stay there where it is, even if newcomers doesn't interested in it.
(I try to find the issue/e-mail thread, but @eteq probably remembers it).

**Comment by bsipocz** [comment]
Here is one of the threads: https://groups.google.com/forum/#!topic/astropy-dev/URiSCJsMCbg

**Comment by abostroem** [comment]
Here are some before (left or top) and after (right or bottom) of the major changes we made.

Top Menu
screen shot 2017-05-12 at 11 32 01 am

Landing page
screen shot 2017-05-12 at 11 27 22 am

Getting Help
screen shot 2017-05-12 at 11 27 54 am

About/Overview
screen shot 2017-05-12 at 11 28 29 am

**Comment by taldcroft** [comment]
Would it be possible to make this live somewhere for review?

**Comment by abostroem** [comment]
I'd be happy to, but I'm not sure how...

**Comment by saimn** [comment]
@abostroem - In the settings of your fork, you can activate the [Github Pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#default-source-settings-for-repositories-without-the-username-naming-scheme) feature. You just have to select the master branch as *Source*, then your version of the website will be available at  https://abostroem.github.io/astropy.github.com/

**Comment by taldcroft** [comment]
If you don't get that working I can also just get your branch and view locally.  But it reduces overall team effort if you can publish the new site to look at.

**Comment by abostroem** [comment]
Done. https://abostroem.github.io/astropy.github.com/

**Comment by mwcraig** [comment]
This looks good to me -- I like the emphasis on getting help. I think the affiliated package page could use a little attention, but I'll open a separate issue for that.

**Comment by eteq** [comment]
(Oh, and it looks like https://github.com/astropy/astropy.github.com/commit/cb7ec8fb90e04ac559a4df6209d7182f3c45e4bb introduced a conflict with this branch... should be pretty easy as it's just an added section, but rebasing might help, @abostroem)

**Comment by eteq** [comment]
Oh, and I think this is meant as a companion to astropy/astropy#6051, right? (I.e., some of the info from the docs removed there is in here)

**Comment by eteq** [comment]
(FYI it looks like https://github.com/astropy/astropy.github.com/commit/cb7ec8fb90e04ac559a4df6209d7182f3c45e4bb introduced a conflict with this branch... should be pretty easy as it's just an added section, but rebasing might help, @abostroem)

**Comment by abostroem** [comment]
@bsipocz I've added team back to the top menu

@eteq 
- Older documentation: I think this belongs as a link from landing page of the docs rather than the home page. It makes sense to me to put a single documentation link here. What do you think @kelle ?

- Current version: We do have a link to What's new in astropy 1.3. This could say 1.3.2. I think this implies that this is the current version and further documentation belongs in the documentation section. What do you think @kelle ?

- I've changed Docs to Documentation to make it more visible.

- Please acknowledge link: to be honest I've never noticed that. I added back near its previous location

- Orange buttons: I do like the short description and the note to cite at the top. I don't like the orange buttons (personal preferences). I've removed the about astropy section since that's in the about page and added back the 1 sentence description and note to cite. Then the first item on the page is What's new in Astropy 1.3

I'll work on rebasing next.

**Comment by abostroem** [comment]
I merged in the changes to contributing. I don't think I need to rebase - let me know if I'm incorrect. Also, I updated the gh-pages website so you can preview the new version with the link above.

**Comment by abostroem** [comment]
Yes, these changes should be merged at the same time as: astropy/astropy#6051 as content is being moved from between these two sites

**Comment by bsipocz** [comment]
@abostroem @eteq - I've made a 1.0.13 and a 1.3.3 release yesterday. Is it OK to update the links in the current pages, or this is foreseen to go in soon, so better to do the updates here?

**Comment by abostroem** [comment]
@bsipocz I think these changes are close, but I'm not sure about the state of astropy/astropy#6051. @eteq @kelle . For this PR, it shouldn't be hard to merge in an updated version.

**Comment by kelle** [comment]
I think this looks GREAT!  I agree that there could be more tweaks, but I think we should merge this PR ASAP.
- I agree with @abostroem that there should not be links to older versions of the documentation on the home page but I also think that we could expose the links to the older documentation better. I don't think the solution is obvious. Can me make this a new issue?
- I am not sure what I think about exposing the latest version. Maybe we want to add a links somewhere to the Change Log and release calendar? Again, I think this could be addressed in a new issue. 
@eteq , is this satisfactory resolution to your comments. This PR is more about the overall organization.
- Regarding astropy/astropy#6051, I won't have time to address all the comments brought up there but my thinking is the same -- merge the PR and move the details into new issues to be addressed at a later date.
This is me punting: 🏈🏃🏽‍♀️

**Comment by kelle** [comment]
The Sphinx doc update PR has been merged (astropy/astropy#6051.) and I resolved the conflict with index.html. I think this PR is good to go!

**Comment by granttremblay** [comment]
This looks really good to me - thanks so much for your work on this!

**Comment by eteq** [comment]
@abostroem @kelle
> I agree with @abostroem that there should not be links to older versions of the documentation on the home page but I also think that we could expose the links to the older documentation better. I don't think the solution is obvious. Can me make this a new issue? 

I think the problem is really that there's no way to expose the links to the older docs from the docs themselves because of how ReadTheDocs is structured.  But agreed that it's fine to merge this now and I'll  make a separate PR to make my suggested solution.

> I am not sure what I think about exposing the latest version. Maybe we want to add a links somewhere to the Change Log and release calendar? Again, I think this could be addressed in a new issue.

Same here - OK with merging and treating this separately.

FWIW, I'm a bit unhappy with the "wall of text" problem still... But again, I agree better to merge this now and treat that as a separate issue. So I'll go ahead and merge now - thanks @abostroem  !

**Pull request merged**
