### PR TITLE
Use PyPI badge for current release version

### PR DESCRIPTION
**Pull request by pllim**
Follow up of #405 . Thanks to @saimn for the idea.

### CODE REVIEW

**Comment by astrofrog** [comment]
This is a good idea but the style is a bit out of place. Is there any way to customise it?

**Comment by saimn** [comment]
https://shields.io/ offers some customization options.

**Comment by pllim** [comment]
If you have one in mind, gimme the new URL or feel free to push to this PR. Thanks!

**Comment by pllim** [comment]
@astrofrog , exactly how you want it customized?

**Comment by pllim** [comment]
I thought this would be nice but seems like release managers don't want it, so closing.

**Comment by bsipocz** [comment]
Fyi: I very much think that this is much better than the manual updates for the number...

**Pull request closed without merging**
