### PR TITLE
Proposed affiliated package: EinsteinPy

### PR DESCRIPTION
**Pull request by shreyasbapat**
EinsteinPy is an open source pure Python package dedicated to problems arising in General Relativity, relativistic physics and gravitational astronomy, such as goedesics plotting for schwarzschild space-time model, calculation of schwarzschild radius for any mass given, symbolic calculation of various functions related to GR such as christoffel symbols. Features like visualization of geodesics of curved black holes and 3D visualizations are some of the features which are planned. It is released under the MIT license. 

Documentation: https://docs.einsteinpy.org

### CODE REVIEW

**Comment by astrofrog** [comment]
Thank you for proposing this package to the Astropy affiliated package ecosystem! We will be asking a member of the Astropy project to review this submission and will get back to you once we hear back from them.

**Comment by shreyasbapat** [comment]
> Thank you for proposing this package to the Astropy affiliated package ecosystem! We will be asking a member of the Astropy project to review this submission and will get back to you once we hear back from them.

Sure ! Thanks @astrofrog

**Comment by astrofrog** [comment]
This package has been reviewed for inclusion in the Astropy affiliated package ecosystem by a member of the Astropy community as well as myself, and I have synthesized the results of the review here.

You can find out more about our review criteria in [Reviewing affiliated packages](https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md). For each of the review categories below we have listed the score and have included some comments when the score is not green.

<table>
<tr><td><b>Functionality/Scope</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#functionality-functionality">
Specialized package
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Integration with Astropy ecosystem</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#integration-with-astropy-ecosystem--ecointegration">
Orange
</a></td></tr>

<tr><td colspan=2><i>EinsteinPy units throughout, though in <code>units.py</code> it might
help to define equivalencies rather than conversion functions. The code
could use more of other parts of astropy. In particular, in constants.py
and bodies.py, the masses of the Sun and Earth should just be taken from
astropy.constants, and the cosmological constant from
astropy.cosmology. We would also strongly recommend to have a look at
  <code>astropy.coordinates.representations</code> - the Spherical and Cartesian
coordinate classes there are more powerful than the corresponding
classes in EinsteinPy.  Somewhat similarly, though not related to
  astropy, <code>integrate.py</code> could use <a href="https://docs.scipy.org/doc/scipy/reference/integrate.html">scipy.integrate</a>
rather than redefine a Runge-Kutta method.</i></td></tr>

<tr><td><b>Documentation</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#documentation-documentation">
Green
</a></td></tr>

<tr><td colspan=2><i>The user documentation is excellent. It would help
to have a bit more for developpers, i.e., expand the EinsteinPy API
section to include class diagrams, etc.  We suggest looking into
  <a href="https://github.com/astropy/sphinx-automodapi">sphinx-automodapi</a>
  to simplify the generation of the API docs.</i></td></tr>

<tr><td><b>Testing</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#testing-testing">
Green
</a></td></tr>

<tr><td colspan=2><i>The tests seems thorough. We would suggest adding tests for
array-valued inputs to the classes; some likely already are able to
handle it, for others it will show easy improvements.</i></td></tr>

<tr><td><b>Development status</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#development-status-devstatus">
Heavy Development
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Python 3 compatibility</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#python-3-compatibility-python3">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

</table>

One thing we would strongly recommend is to aim at handling array-valued inputs in all classes, broadcasting inputs as necessary.  This is also another reason to base the coordinate classes on
``astropy.coordinatates.representatations`` – those should give good examples for how to ensure this works.  Relatedly, we would recommend  ensuring one does not use numpy arrays to store disparate elements (as in the outputs of many Kerr methods such as ``f_vec``).

**Summary/Decision**: This package meets the review criteria for affiliated packages, so we are happy to confirm that we'll be listing your package as an affiliated package! Keep up the good work, and we encourage you to improve on the areas above that weren't “green” yet.

If you have any follow-up questions or disagree with any of the comments above, leave a comment and we can discuss it here. At any point in future you can request a re-review of the package if you believe any of the scores should be updated - contact the coordination committee, and we will do a new review.

**Comment by shreyasbapat** [comment]
Amazing! Thanks a lot @astrofrog :)

**Pull request merged**
