### PR TITLE
Proposed affiliated package: BayesicFitting

### PR DESCRIPTION
**Pull request by dokester**
From the abstract of our paper (DOI : 10.1016/j.ascom.2021.100503) we cite:

BayesicFitting is a comprehensive, general-purpose toolbox for simple and standardized model fitting. Its fitting options range from simple least-squares methods, via maximum likelihood to fully Bayesian inference, working on a multitude of available models. BayesicFitting is open source and has been in development and use since the 1990s. It has been applied to a variety of science applications, chiefly in astronomy.

BayesicFitting consists of a collection of PYTHON classes that can be combined to solve quite complicated inference problems. Amongst the classes are models, fitters, priors, error distributions, engines, samples, and of course NestedSampler, our general-purpose implementation of the nested sampling algorithm.

Nested sampling is a novel way to perform Bayesian calculations. It can be applied to inference problems, that consist of a parameterized model to fit measured data to. NestedSampler calculates the Bayesian evidence as the numeric integral over the posterior probability of (hyper)parameters of the problem. The solution in terms of the parameters is obtained as a set of weighted samples drawn from the posterior.

### CODE REVIEW

**Comment by hamogu** [comment]
Thank you for proposing this package as an affiliated package! We are currently looking for a reviewer. I will post updates here when I hear back from potential reviewers.

**Comment by hamogu** [comment]
Thank you for proposing this package as an affiliated package! I'm happy to confirm that your package is now under review and we'll post the results of the review here and on the mailing list.

**Comment by dhomeier** [comment]
This package has been reviewed for inclusion in the Astropy affiliated package
ecosystem by a member of the Astropy community as well as @hamogu and myself, and I have
synthesised the results of the review here.

You can find out more about our review criteria in
[Reviewing affiliated packages](https://github.com/astropy/astropy-procedures/blob/main/documents/affiliated_package_review_guidelines.md).
For each of the review categories below we have listed the score and have
included some comments when the score is not green.

<table>
<tr><td><b>Functionality/Scope</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/main/documents/affiliated_package_review_guidelines.md#functionality-functionality">
General package
</a></td></tr>

<tr><td colspan=2><i>Model fitting and Bayesian evidence calculation based on original Java code from the Herschel Common Science System, but with more general applicability.</i></td></tr>

<tr><td><b>Integration with Astropy ecosystem</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/main/documents/affiliated_package_review_guidelines.md#integration-with-astropy-ecosystem--ecointegration">
Orange
</a></td></tr>

<tr><td colspan=2><i>Implementation of all model and fitter methods independent from `astropy.modelling`. Several Model classes have a method to return units. These methods are limited to returning
`Unit(1)`, i.e. `dimensionless` unit. There is no unit propagation in the models.
This is the only use of astropy in the package.
It is at this point designed to be usable as a standalone package, but also implements some functionality still missing in `astropy.modeling`.
</i></td></tr>

<tr><td><b>Documentation</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/main/documents/affiliated_package_review_guidelines.md#documentation-documentation">
Green
</a></td></tr>

<tr><td colspan=2><i>There is extensive documentation with a large set of example Notebooks and a recent publication in <a href="https://doi.org/10.1016/j.ascom.2021.100503">Astronomy and Computing</a> describing the package in detail.</i></td></tr>

<tr><td><b>Testing</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/main/documents/affiliated_package_review_guidelines.md#testing-testing">
Orange
</a></td></tr>

<tr><td colspan=2><i>There are many tests in the package.
The tests don’t run automatically and no test coverage tool is run with the standard setup, which is based on `unittest`.
Running them under `pytest` is possible, but requires some manual adjustments; running then with coverage shows all submodules apart from `utils` to have >90% coverage.

The tests also take a long time to run. Some of the code may be written more efficiently, and a few large tests that seem to take most of the runtime could be marked as `slow` with a little extra integration of `pytest`.</i></td></tr>

<tr><td><b>Development status</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/main/documents/affiliated_package_review_guidelines.md#development-status-devstatus">
Green
</a></td></tr>

<tr><td colspan=2><i></i>The package is on github since 2018. Since then there have been no code contributions as Pull Requests (PRs). There were 6 minor PRs related to code management. There are also no open issues (8 closed since 2018).

There are regular contributions to the main branch by the single author and it looks like the code is actively 
maintained by him with the latest release on PyPi from Nov 25th, 2021.
</td></tr>

<tr><td><b>Python 3 compatibility</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/main/documents/affiliated_package_review_guidelines.md#python-3-compatibility-python3">
Green
</a></td></tr>

<tr><td colspan=2><i>Written for Python 3 from the start and pip-installable for 3.10</i></td></tr>

</table>

**Other notes**: I think this is a remarkable work done by mostly one developer over many years. It has a lot of value and some parts fill in a gap of functionality that is not available in the astropy ecosystem.

That said there’s substantial duplication of functionality with astropy in specific models and fitters. What astropy is missing is the samplers and evidence computation in BayesicFitting. Ideally someone (best would be if this is the author) adapts those and contributes them to astropy core. There’s currently an effort to add samplers to astropy modeling, so those efforts can be combined. IMHO it’s best if the author gets involved in this effort so he becomes an astropy contributor and gets the credit for the work.

**Summary/Decision**: This package meets the review criteria for affiliated
packages, so we are happy to confirm that we'll be listing your package as an
affiliated package! Keep up the good work, and we encourage you to improve on
the areas above that weren't “green” yet.

As an integration of some of its core classes into the Astropy core `modeling` module would eventually benefit both packages in terms of functionality and long-term maintainability, the we hope to work out the details of such future development in coordination with the maintainers.

If you have any follow-up questions or disagree with any of the comments above,
leave a comment and we can discuss it here. At any point in future you can
request a re-review of the package if you believe any of the scores should be
updated - contact the affiliated package editors
[listed on the Astropy team page](https://www.astropy.org/team),
and we will do a new review.

**Comment by dokester** [comment]
First of all thanks for granting BayesicFitting (BF) the Astropy affiliated package status. I hope this will be a fruitful association. 

Allow me some comments on the 2 orange items.
1. Integration with the Astropy ecosystem.
Agreed, there is not much. When I started BF I thought it would be nice to implement units. And I found that Astropy had already a complete package, so I started using it. But the only thing it does is return the units for the parameters, given the units for the independent and dependent variables (resp. x and y). I never found a good use case for it so it did not get any further development. Later I added the option to use an Astropy Table as input for x. Again little else was added or developed. Recently I wrote a wrapper model, AstropyModel, to encapsulate a FittableModel from astropy.modeling such that it can be used with the BF fitters and samplers. It even can be combined with a BF-Model to form a BF compound model. 
2. Testing.
The use of 'unittest' I took over from HCSS, Herschel Common Software System which contained the fit toolbox, BF's predecessor. I only needed to provide the unit test cases. The integration into an automatic system was done by the ESA people. I never learned how to do it. I just ran individual tests when working on a particular class. 
Before delivering an update of BF, all tests are run in a script, making sure everything works. It is true that it takes some time to run them all, about 40 min on my Macbook M1 (much longer on my previous Macbook). I dont care too much; take a cup of coffee and let the dog out. The long run time is mostly due to several long runs of NestedSampler. I could shorten them by limiting the number of iterations. However some errors only popped up after more than 1000 iterations. Shortcutting the tests would not have found them. Maybe I can have both options. Quickies for daily use and full blown tests before delivering. 
Is it PYTEST that I need to use or would you advise something else.

I leave it for now. Shortly I will add my thoughts about integration of BF and Astropy modeling.

**Comment by dokester** [comment]
I added some comments in  #451 <https://github.com/astropy/astropy.github.com/pull/451> 

Sending this email as I am not sure if you will be noticed automatically.

Do Kester

**Comment by pllim** [comment]
> Is it PYTEST that I need to use or would you advise something else

Hello! Yes, we recommend `pytest` if it is possible. It has more features than Python's built-in `unittest` and the other testing package, `nosetest`, is no longer being developed.

**Pull request merged**
