### PR TITLE
Replace PyVO webpage link

### PR DESCRIPTION
**Pull request by smoh**
The old link is dead, and this seems to be the new one. Pinging the maintainer in case I'm wrong @RayPlante

### CODE REVIEW

**Comment by adrn** [comment]
@pllim could you take a look at this?

**Comment by pllim** [comment]
LGTM. It is consistent with the URL provided in https://github.com/pyvirtobs/pyvo .

**Comment by pllim** [comment]
Maybe @funbaker can have a look since he has been developing over there.

**Comment by adrn** [comment]
Since the old link doesn't even work, I'm going to merge...

**Comment by funbaker** [comment]
This is fine.

**Pull request merged**
