### PR TITLE
Updated voting member list

### PR DESCRIPTION
**Pull request by eteq**
Note this is for those of the "initial" cohort who responded after #431 was merged (up to today, at least!)

cc @Cadair @ceb8 @mwcraig

### CODE REVIEW

**Review by Cadair — COMMENTED** [review]
What is with the indentation on this diff :p

**Comment by eteq** [comment]
> What is with the indentation on this diff :p

While normally I'd be all for pedantic whitespace suggestions, @Cadair  :wink: ... in this case, I'm confused because it looks like it's the same as the other lines to me...?

**Comment by Cadair** [comment]
Maybe its the android app lying to me 🤔

**Comment by eteq** [comment]
Weird!  This is what I see in my regular text editor:
image
which seem right :shrug: .  Anyway, please approve if it looks to you @Cadair ! (since I prefer at least one approval for my own PRs...)

**Review by Cadair — APPROVED** [review]

**Comment by ceb8** [comment]
It also looks normal to me. 😛

**Pull request merged**
