### PR TITLE
DOC: Replace astropy channel with conda-forge

### PR DESCRIPTION
**Pull request by pllim**
Similar to astropy/astropy#11111

cc @mwcraig

### CODE REVIEW

**Comment by pllim** [comment]
I thought we agreed on this, so I don't know what the hold up is.

**Comment by mwcraig** [comment]
Is there a need to merge this if we merge astropy/astropy#11111? 

It doesn't seem like the 4.1 release announcement is the place that needs the fix given how long ago that was....

**Comment by pllim** [comment]
Oh yah... Let's just close this then. When we finally really want to do this, me or some other person can open a new PR.

**Comment by pllim** [comment]
Looks like last release announcement already uses conda-forge, so maybe we don't need this:

https://github.com/astropy/astropy.github.com/blob/2b68f19840ac89bcdb179adf64201db55f868ba3/announcements/release-4.3.html#L143

**Pull request closed without merging**
