### PR TITLE
Updating spherical geometry maintainer in registry

### PR DESCRIPTION
**Pull request by bsipocz**
This came up while updating the table for the astropy paper.

### CODE REVIEW

**Comment by bsipocz** [comment]
If there is any more outdated information in the registry file, please let me know so I'm aware when updating the paper.

**Comment by pllim** [comment]
I did the same deletion in #232. I wasn't aware of this PR then. FYI.

**Comment by bsipocz** [comment]
Well, I wasn't aware that you already made the change. Anyway, if @eteq is happy with #232 and merge it, we can easily close this.

**Comment by bsipocz** [comment]
Closing as it was done in #232.

**Pull request closed without merging**
