### PR TITLE
Nominate new affiliated package editor

### PR DESCRIPTION
**Pull request by hamogu**

### CODE REVIEW

**Review by pllim — APPROVED** [review]

**Comment by pllim** [comment]
cc @WilliamJamieson

**Comment by WilliamJamieson** [comment]
I accept this nomination.

**Comment by hamogu** [comment]
Great! We'll just leave it open for 2 weeks as APE0 says in case anybody will comment and then I'll merge.

**Comment by mwcraig** [comment]
Thanks for volunteering to do this @WilliamJamieson

**Comment by hamogu** [comment]
This has been open for two week (in fact a little longer, since I was on vacation in early January). Welcome our new affiliate editor @WilliamJamieson

**Pull request merged**
