### PR TITLE
astroalign affiliated package request

### PR DESCRIPTION
**Pull request by martinberoiz**

### CODE REVIEW

**Comment by astrofrog** [comment]
Thank you for proposing this package to the Astropy affiliated package ecosystem! I'm very sorry about the delay in getting this package reviewed 🙏 - as you know we have been working on finalizing a [new review workflow](https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_process.md) and have only just managed to finalize it.

Could you add empty sections to the ``review`` section as described in [proposing an affiliated package](https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_process.md#proposing-an-affiliated-package)? I'll be assigning a reviewer shortly for this package, and will get back to you soon.

**Comment by martinberoiz** [comment]
Hi,
I added the empty review portion and moved my package to the top, as it's described in the link you provided. If I need to modify it somehow just let me know.

Thanks for your consideration, have a nice day.

**Comment by astrofrog** [comment]
This package has been reviewed for inclusion in the Astropy affiliated package ecosystem by a member of the Astropy community as well as the coordination committee, and we have synthesized the results of the review here.

You can find out more about our review criteria in [Reviewing affiliated packages](https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md). For each of the review categories below we have listed the score and have included some comments when the score is not green.

<table>
<tr><td><b>Functionality/Scope</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#functionality-functionality">
Specialized package
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Integration with Astropy ecosystem</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#integration-with-astropy-ecosystem--ecointegration">
Red
</a></td></tr>

<tr><td colspan=2><i>
At the moment astroalign has no integration with the astropy ecosystem. We are looking for some or all of the following:<br><br>
<ul>
<li>Depends on astropy or other parts of the astropy ecosystem.
<li>Accepts core data types from astropy or other parts of the astropy ecosystem.
<li>Provides documentation on how to interact with other parts of astropy.
</ul>
For example, currently astroalign relies on SEP internally to do the photometry, but there is no reason why this couldn't make use of photutils (to be clear, having an option to select which photometry tool to use would be fine). Another place where more integration is possible is in what inputs can be specified - for example it would be good if CCDData (or more generically NDData) objects from the core astropy package could be used. One last example is that tabular input could be specified using astropy tables (e.g. for estimate_transform). <br><br> Integration doesn't have to always be code though. You could instead show example in the documentation about how to use astroalign with Table, NDData, and so on, so that users familiar with the rest of the astropy ecosystem will see how this can fit into their workflow. Once there is some effort in terms of integration (and partial integration would be sufficient for acceptance), we'd of course be happy to re-review this package.<br><br>
Don't hesitate to ask if you want some more ideas, either here or in separate issues, for how to improve integration.
<tr><td><b>Documentation</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#documentation-documentation">
Orange
</a></td></tr>

<tr><td colspan=2><i>The narrative documentation on ReadTheDocs are good, and there is a link to a sample notebook in the README for the package. We would recommend including a link to the notebook in the narrative documentation too.
For now, we are rating the documentation as orange because the API documentation is missing (which means we can't click on function names to read their detailed documentation), and could easily be added by using sphinx-automodapi.</i></td></tr>

<tr><td><b>Testing</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#testing-testing">
Green
</a></td></tr>

<tr><td colspan=2><i>Tests are run using unittest, and codecov reports > 90% coverage. Tests currently require to package to be installed
before running. It would be more convenient if that wasn't the case, but not critical. </i></td></tr>

<tr><td><b>Development status</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#development-status-devstatus">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Python 3 compatibility</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#python-3-compatibility-python3">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

</table>

**Additional comments**: The reviewer ran the alignment on a couple of images and it worked. One issue that should be addressed in the documentation however is whether flux is conserved in the image transform. While it is of course entirely up to the package author whether to consider this, it might be worth approaching the ccdproc maintainers as they might welcome including this functionality in ccdproc.

**Summary/Decision**: Thanks for your work on this package! Unfortunately, one of the review areas came in as red. As per the review guidelines, we therefore won't be able to accept this package as an affiliated package yet. We will leave this pull request open for a month in case you would like to respond to the comments and/or address any of them. As mentioned above, we'd be happy to discuss the integration aspect more, either in this pull request or in separate issues. 

If you have any follow-up questions or disagree with any of the comments above, leave a comment and we can discuss it here. At any point in future you can request a re-review of the package if you believe any of the scores should be updated - contact the coordination committee, and we’ll do a new review.

**Comment by martinberoiz** [comment]
I apologize I just saw this after so many months!
Thank you for your extensive review! I appreciate the effort. I will work over the summer on improving compatibility and will reapply after.
Thanks.

**Comment by martinberoiz** [comment]
Hello,

I just released a release candidate for my version (2.0) of astroalign (not on PyPI yet). 
It basically addresses these two points:

> - Accepts core data types from astropy or other parts of the astropy ecosystem.
> - Provides documentation on how to interact with other parts of astropy.

I had to bump main version number because I break the API (unrelated to this PR, that's something I wanted to implement long ago.)

Please check the [new documentation](https://astroalign.readthedocs.io/en/latest/tutorial.html#dataobjs)
and tell me if you have any suggestions on how to improve it.

The relevant new code is [here](https://github.com/toros-astro/astroalign/blob/d88439de7c523e59c91ee0d72c67c9157f823e28/astroalign.py#L275-L304).

Regarding using photutils instead of sep, I still cannot make it work to my satisfaction (one of my tests fails erratically), so it's still work in progress.

I also plan to add in the future integration with astropy's Table as input.

I would like to hear your input before I go public on this version.

Thanks!

**Comment by astrofrog** [comment]
@martinberoiz - I'll take a look at the new version shortly - thanks!

**Comment by astrofrog** [comment]
@martinberoiz - the integration with ``NDData`` and ``CCDData`` is an improvement, thanks! (and sorry for the delay in getting back to you). Once the new release is out, let me know and I will update the review here to change the integration score to orange.

**Comment by martinberoiz** [comment]
Great! thanks. I'll let you know.

**Comment by martinberoiz** [comment]
I have a question regarding the evaluation. I couldn't understand this part

> For now, we are rating the documentation as orange because the API documentation is missing (which means we can't click on function names to read their detailed documentation), and could easily be added by using sphinx-automodapi.

I thought this was covered here https://astroalign.readthedocs.io/en/latest/api.html, but now I think it may refer to something else? Could you help me with this?

Thanks.

**Comment by martinberoiz** [comment]
I just released version 2.0, it's publicly available and the docs are updated as well.

**Comment by astrofrog** [comment]
I've now updated the review as follows:

<table>
<tr><td><b>Functionality/Scope</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#functionality-functionality">
Specialized package
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Integration with Astropy ecosystem</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#integration-with-astropy-ecosystem--ecointegration">
Orange
</a></td></tr>

<tr><td colspan=2><i>
At the moment astroalign has some integration with e.g. <code>NDData</code>, but more work could be done in this direction. For example, currently astroalign relies on SEP internally to do the photometry, but there is no reason why this couldn't make use of photutils (to be clear, having an option to select which photometry tool to use would be fine). Another example is that tabular input could be specified using astropy tables (e.g. for <code>estimate_transform</code>) and there could be some integration with <code>astropy.coordinates</code> too for specifying star positions.
<tr><td><b>Documentation</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#documentation-documentation">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Testing</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#testing-testing">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Development status</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#development-status-devstatus">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

<tr><td><b>Python 3 compatibility</b></td><td>
<a href="https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md#python-3-compatibility-python3">
Green
</a></td></tr>

<tr><td colspan=2><i>No further comments</i></td></tr>

</table>

**Additional comments**: The reviewer ran the alignment on a couple of images and it worked. While it is of course entirely up to the package author whether to consider this, it might be worth approaching the ccdproc maintainers as they might welcome including this functionality in ccdproc.

**Summary/Decision**: This package meets the review criteria for affiliated packages, so we are happy to confirm that we'll be listing your package as an affiliated package! Keep up the good work, and we encourage you to improve on the areas above that weren't “green” yet.

If you have any follow-up questions or disagree with any of the comments above, leave a comment and we can discuss it here. At any point in future you can request a re-review of the package if you believe any of the scores should be updated - contact the coordination committee, and we’ll do a new review.

**Comment by astrofrog** [comment]
The CircleCI failure is unrelated and due to https://github.com/RiceMunk/omnifit/issues/44

**Pull request merged**
