### PR TITLE
Update affiliated package repo with information gathered over summer

### PR DESCRIPTION
**Pull request by mwcraig**
This PR makes two changes:

+ Update some details of affiliated package entries that were generated while working on the numfocus affiliated package blog post this past summer.
+ Adds two new keys to the json entries: `image` and `educational_materials_link`

I can separate this into two PRs if you would like.

### CODE REVIEW

**Comment by eteq** [comment]
@mwcraig - I rebased this for you because I had just  merged #185 which made a conflict.

On the extra tags, I like `image`, but am not clear on `educational_materials_link` - I guess it's not clear to me why we should have that in addition to documentation?

**Comment by mwcraig** [comment]
Double check with @kelle, but I think the intent was that as packages develop more tutorial-like material the `educational_materials_link` can be a gateway to that, and can (perhaps) become an explicit target that affiliated packages should aim for.

That said, I do not think it should be *displayed* now, or perhaps only for the 1 or 2 packages that have something concrete.

**Comment by eteq** [comment]
@mwcraig - understood.  My main concern is that it might be a source of confusion for new affiliated package authors. Unlike all the other terms it's not really immediately obvious what belongs there.  So I wonder if an explanation of it should go somewhere?

(Or you can split just this out in a separate PR if it requires more thought/discussion, as all the rest looks good)

**Comment by astrofrog** [comment]
@mwcraig - can you rebase and split out the educational stuff for now so we can discuss it separately? The other changes look good.

**Comment by mwcraig** [comment]
Will update tonight

On Wed, Sep 27, 2017 at 4:09 AM, Thomas Robitaille <notifications@github.com

**Comment by mwcraig** [comment]
rebase/edits are done

**Comment by astrofrog** [comment]
Thanks @mwcraig!

**Pull request merged**
