### PR TITLE
Complete the record for sbpy affiliated package

### PR DESCRIPTION
**Pull request by olebole**
This PR sets the `pypi_name` and `provisional` fields for sbpy.
The package is on Pypi ([tested](https://pypi.org/project/sbpy/)), and this is mentioned in the `README.md`.
For `provisional` I just assumed that it is non-provisional since this status is nowhere mentioned. BTW, the [review docs](https://github.com/astropy/astropy-procedures/blob/65d45d3d48ea0f4629c5e565a10479d009e54928/documents/affiliated_package_review_guidelines.md) do not mention the `provisional` status flag -- what are the criteria here?

### CODE REVIEW

**Comment by bsipocz** [comment]
the `provisial` status has been removed in favour of the colour coding: https://github.com/astropy/astropy-procedures/blob/master/documents/affiliated_package_review_guidelines.md

**Comment by olebole** [comment]
Ah, OK. sbpy was the only package without that field. That leaves the `pypi_name` only.

**Comment by bsipocz** [comment]
Yes, I suppose this file might have not yet been cleaned up.

cc @astrofrog

**Comment by bsipocz** [comment]
Thanks @olebole!

**Pull request merged**
