### PR TITLE
Add MaLTPyNT to affiliated registry

### PR DESCRIPTION
**Pull request by matteobachetti**
I would like to propose the MaLTPyNT code as an affiliated package.
This set of libraries and scripts was originally written with the timing properties of the NuSTAR X-ray mission in mind, but it is easily usable with event lists from other X-ray missions or light curves from any instrument.
It makes it possible to calculate light curves starting from event lists, power density spectra, cross spectra and derivatives, and time lags starting from event lists or lightcurves in FITS or text format, from X-ray datasets, and to simulate dead-time affected datasets.

The code is structured according to the Astropy template, and documented following most of the Astropy Guidelines. Astropy functions are used mostly for for FITS handling and time conversions. 
It is distributed through a bitbucket repository (https://bitbucket.org/mbachett/maltpynt) mirrored on GitHub (https://github.com/matteobachetti/MaLTPyNT). The documentation can be found here: http://maltpynt.readthedocs.org/en/latest/. Tests are run with Travis CI (https://travis-ci.org/matteobachetti/MaLTPyNT) and Appveyor (https://ci.appveyor.com/project/matteobachetti/maltpynt).  Python 2.7, 3.3 and 3.4 are supported. Stable releases are deployed to pypi (maltpynt).

Thanks in advance for your consideration.

### CODE REVIEW

**Comment by eteq** [comment]
@matteobachetti, can you please post your affiliated package request to [astropy-dev](https://groups.google.com/forum/#!forum/astropy-dev) as per the [standard procedure](affiliated.astropy.org/#affiliated-instructions) so that we have the record of the request?  Thanks!

**Comment by matteobachetti** [comment]
@eteq I did that already:
https://groups.google.com/forum/m/#!topic/astropy-dev/tDzLHx_4AHk

**Comment by matteobachetti** [comment]
@eteq I was wondering if you had the time to take a look? Thanks in advance

**Comment by eteq** [comment]
@matteobachetti - sorry about that - you got lost a bit in the shuffle as we were transitioning coordination committee members.  Now that we're a bit more settled, will try to get you the final answer.

**Pull request merged**
